### ISSUE TITLE
Error while Setup/Satrting

### ISSUE THREAD

**Issue by Solilord** [wine-gameservers/arch-fs25server#2]
Hi! 
I get these errors when setting up the game:

preloader: Warning: failed to reserve range 00010000-00110000
wine: socket : Function not implemented

Also the symlink creation throws this:
ln: failed to create symbolic link '/home/nobody/.fs25server/drive_c/Program Files (x86)/Farming Simulator 2025': No such file or directory

But when i use the exact command from the script in terminal, the symlink gets created...

Latest Docker version running on a ubuntu root server.
privilege mode and seccomp:unconfined didnt work so far

**Comment by Toetje585** [comment]
I would start the container using docker-compose up to get more logging. Or you can alter the Setup shortcut to enable "run in terminal" Also do not run docker containers as root.

**Comment by Solilord** [comment]
I already did. 
In all logs, when executing wine commands on its own: always the two errors 
```
preloader: Warning: failed to reserve range 00010000-00110000
wine: socket : Function not implemented
```

**Comment by Toetje585** [comment]
> I already did. In all logs, when executing wine commands on its own: always the two errors
> 
> ```
> preloader: Warning: failed to reserve range 00010000-00110000
> wine: socket : Function not implemented
> ```

What kind of root server is this, it must be something they configured.

**Comment by Solilord** [comment]
Virtual Server (Virtuozzo based), Ubuntu 22.04
with Plesk
Hosted by Strato

Other appliances are working well. (e.g. other games servers (with and without docker), Webservers etc)

**Comment by Toetje585** [comment]
Are you running the containers as root user?

**Comment by Toetje585** [comment]
Closing: If help is still needed please seek help in our Discord.
