### ISSUE TITLE
Game not found after cotainer recreated

### ISSUE THREAD

**Issue by LsHallo** [wine-gameservers/arch-fs25server#3]
I've successfully installed the game and could play on the server.
However after a recreate of the docker container it reports: `Game not installed?`
The game is mounted on /opt/fs25/game like your compose suggests.
But the startup bash script checks `~/.fs25server/drive_c/Program\ Files\ \(x86\)/Farming\ Simulator\ 2025/dedicatedServer.exe` before trying to start with wine when I run Start Server on the Desktop.
Either the container needs some symlinks, the mounting locations needs adjustment or the startup script?

**Comment by LsHallo** [comment]
If I manually go to /opt/fs25/game and start dedicatedServer.exe with wine it starts up fine. So it is not an installation problem.

**Comment by LsHallo** [comment]
I'm also missing my savegames? Please don't tell me they are gone...

**Comment by TimoHocker** [comment]
Happens to me too. Try running the setup script again before the start script. It creates some important symlinks.

**Comment by LsHallo** [comment]
Okay running setup again fixed the starting issue.
But savegame2 is still empty and that's definitely where i saved it...

Had to go to the saveGameBackup folder and restore the latest savegame2 from there. Lost about an hour...

**Comment by Toetje585** [comment]
Closing: If help is still needed please seek help in our Discord.

Perhaps in future we can also let the start script create the symlinks to prevent this.
