### ISSUE TITLE
One or more mods are corrupted

### ISSUE THREAD

**Issue by hrolofs** [wine-gameservers/arch-fs25server#5]
Hi,

many thanks for your work. :-)

I have installed FS25 (installer folder) and New Holland CR11 Gold Edition DLC (dlc folder).

During the initial setup  i entered for the game and for the dlc the license code and everything looks fine. After i started the server the web page shows me thet the Mod "New Holland CR111 Gold Edition" are corrupted.

I need help to fix this.

**Comment by Toetje585** [comment]
This is a bug by Giants, and can't be fixed on my end.

**Comment by DreiPixel** [comment]
having the same issue. cant find anything to fix this.

**Comment by TimoHocker** [comment]
You don't need to fix it. The CR11 gold will still be available in game if you have the dlc on the client. The same happened with the Volvo DLC in FS22
